version: '3.8'

services:
  web:
    build: .
    container_name: web
    depends_on:
      - db
    image: php:7.4-fpm
    volumes:
      - ./site:/var/www/html
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init/db.sql:/docker-entrypoint-initdb.d/db.sql

  proxy:
    image: nginx:latest
    container_name: proxy_container
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Chemin corrigé
      - ./site:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
